import { supabase } from './supabase';

declare global {
  interface Window {
    OneSignalDeferred?: Array<(os: OneSignalSDK) => void | Promise<void>>;
    OneSignal?: OneSignalSDK;
  }
}

interface OneSignalSDK {
  init(opts: {
    appId: string;
    safari_web_id?: string;
    notifyButton?: { enable: boolean };
    allowLocalhostAsSecureOrigin?: boolean;
  }): Promise<void>;
  login(externalId: string): Promise<void>;
  logout(): Promise<void>;
  Notifications: {
    requestPermission(): Promise<boolean>;
    permissionNative: NotificationPermission;
  };
}

function deferred(fn: (os: OneSignalSDK) => void | Promise<void>) {
  window.OneSignalDeferred = window.OneSignalDeferred || [];
  window.OneSignalDeferred.push(fn);
}

export function initOneSignal() {
  deferred(async (os) => {
    await os.init({
      appId: import.meta.env.VITE_ONESIGNAL_APP_ID as string,
      // Generated by completing OneSignal's Web Push setup for this app — required
      // for push to work on Safari/iOS (every browser on iPhone runs Safari's engine).
      safari_web_id: import.meta.env.VITE_ONESIGNAL_SAFARI_WEB_ID as string,
      notifyButton: { enable: false },
      allowLocalhostAsSecureOrigin: import.meta.env.DEV as boolean,
    });
  });
}

export function loginOneSignal(familyId: string) {
  deferred(async (os) => {
    await os.login(familyId);
  });
}

export function logoutOneSignal() {
  deferred(async (os) => {
    await os.logout();
  });
}

export function getPushPermission(): NotificationPermission {
  return window.Notification?.permission ?? 'default';
}

export async function requestPushPermission(): Promise<boolean> {
  // Safari/iOS only shows the native permission popup when requestPermission()
  // runs synchronously inside the triggering user gesture. Call the already-loaded
  // SDK directly (true by the time a user can reach a button that calls this)
  // rather than through the OneSignalDeferred queue, which defers to a later tick
  // and silently loses that trust — no popup, no error.
  if (window.OneSignal?.Notifications?.requestPermission) {
    try {
      return await window.OneSignal.Notifications.requestPermission();
    } catch {
      return false;
    }
  }

  return new Promise((resolve) => {
    let settled = false;
    const finish = (granted: boolean) => {
      if (settled) return;
      settled = true;
      resolve(granted);
    };
    deferred(async (os) => {
      try {
        const granted = await os.Notifications.requestPermission();
        finish(granted);
      } catch {
        finish(false);
      }
    });
    setTimeout(() => finish(getPushPermission() === 'granted'), 8000);
  });
}

export async function sendPush(params: {
  to: 'family';
  familyId?: string;
  title: string;
  body: string;
  url?: string;
}): Promise<void> {
  try {
    await supabase.functions.invoke('send-push-lcp', { body: params });
  } catch {
    // Push failures are non-critical
  }
}
